<script type="text/javascript">
    //<!--
    MW.AdvancedCompare.addToCompareUrl = "<?php echo Mage::getUrl("catalog/product_compare/add") ?>";
    MW.AdvancedCompare.currentUrl = "<?php echo Mage::helper("core/url")->getCurrentUrl()?>";
    MW.AdvancedCompare.elePopupWapper = "#compare_popup_wapper";
    MW.AdvancedCompare.comparePopupUrl = "<?php echo Mage::getUrl("advancedcompare/compare/popup") ?>";
    //-->
</script>