<?php
$_product = $this->getProduct();
?>
<?php if ($_product->getId()): ?>
<div>
    <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart"
            onclick="MW.CartAjax.addToCart(<?php echo $_product->getId() ?>)">
        <span><span><?php echo $this->__('Add to Cart') ?></span></span>
    </button>
    <div id="cartajax-loading-<?php echo $_product->getId(); ?>" style="float:right;padding: 2px;display: none">
        <img src="<?php echo $this->getSkinUrl("images/mw/cartpro/ajax-loader-circle.gif") ?>"/>
    </div>
</div>
<?php else: ?>
    Error
<?php endif; ?>

