<?php
/**
* @category   MW
* @package    MW_Core
* @version    1.0.0
* @copyright  Copyright (c) 2012 Magento Whiz. (http://www.magentowhiz.com)
*/
?>
<?php $_product = $this->getProduct();?>
<?php if ($_compareUrl = $this->getAddToCompareUrl()): ?>
    <li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a></li>
<?php endif; ?>