<div id='product_option_popup_wapper'>
    <a href="javascript:void(0)" onclick="MW.QuickView.closeProductOption()">Close</a>
    <div id="loadingimage_on_product_option" style="width:100%;height:100%;z-index:999;position: absolute;display: block;background-color: white">
        <img style="position: absolute;top:40%;left:50%" alt="Loading" src="<?php echo $this->getSkinUrl("images/mw/quickview/ico-loading.gif") ?>">
    </div>
    <iframe></iframe>
</div>