<script type="text/javascript">
    //<!--
    MW.QuickView.eleWapper = "#quickview_popup_wapper";
    MW.QuickView.quickViewUrl = "<?php echo Mage::getUrl("quickview/popup/view") ?>";
    MW.QuickView.eleImageLoading = "#loadingimage_on_quickview";

    MW.QuickView.productOptionWapper = "#product_option_popup_wapper";
    MW.QuickView.productOptionUrl = "<?php echo Mage::getUrl("quickview/popup/productoption") ?>";
    MW.QuickView.productOptionImageLoading = "#loadingimage_on_product_option";
    //-->
</script>