<div id='quickview_popup_wapper'>
    <a href="javascript:void(0)" onclick="MW.QuickView.closeQuickView()">Close</a>
    <div id="loadingimage_on_quickview" style="width:100%;height:100%;z-index:999;position: absolute;display: block;background-color: white">
        <img style="position: absolute;top:40%;left:50%" alt="Loading" src="<?php echo $this->getSkinUrl("images/mw/quickview/ico-loading.gif") ?>">
    </div>
    <iframe></iframe>
</div>
<div id="bModal_canvas_quickview" style="display: none;background-color: rgb(0, 0, 0); height: 100%; left: 0px; opacity: 0.6; position: fixed; top: 0px; width: 100%; z-index: 9998; cursor: pointer;"></div>
<script type="text/javascript">
    //<!--
    MW.QuickView.addBeforeQuickViewEvent(function(){
        jQuery("#bModal_canvas_quickview").show();
    });

    MW.QuickView.addCloseQuickViewEvent(function(){
        jQuery("#bModal_canvas_quickview").hide();
    })
    //-->
</script>